default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parsley_development
  username: <%= ENV['PARSLEY_DEVELOPMENT_DB_USERNAME'] %>
  password: <%= ENV['PARSELY_DEVELOPMENT_DB_PASSWORD'] %>
  host: <%= ENV['PARSLEY_DEVELOPMENT_DB_HOST'] %>
  port: 5432

test:
  <<: *default
  database: parsley_test
  username: <%= ENV['PARSLEY_TEST_DB_USERNAME'] %>
  password: <%= ENV['PARSLEY_TEST_DB_PASSWORD'] %>
  host: <%= ENV['PARSLEY_TEST_DB_HOST'] %>
  port: 5432

staging:
  <<: *default
  database: parsley_staging
  username: <%= ENV['PARSLEY_DATABASE_USERNAME'] %>
  password: <%= ENV['PARSLEY_DATABASE_PASSWORD'] %>
  host: <%= ENV['PARSLEY_DATABASE_HOST'] %>
  port: 5432

production:
  <<: *default
  database: parsley_production
  username: <%= ENV['PARSLEY_DATABASE_USERNAME'] %>
  password: <%= ENV['PARSLEY_DATABASE_PASSWORD'] %>
  host: <%= ENV['PARSLEY_DATABASE_HOST'] %>
  port: 5432
